icons_format = "{icon}"

[theme]
theme = "plain"

[icons]
icons = "awesome4"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%d.%m %R') "

[[block]]
block = "battery"
format = " $icon   $percentage {$time_remaining.dur(hms:true, min_unit:m) }"
device = "DisplayDevice"
driver = "upower"
missing_format = ""
interval = 60
info = 101
good = 101
warning = 0 
critical = 0

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0 
alert = 10.0
format = " $icon   $available.eng(w:2) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon   $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pwvucontrol"
