#!/usr/bin/env bash

# Set default values if not already set
STOW_FOLDERS="${STOW_FOLDERS:-zsh,git,bin,git,i3,tmux,nvim,picom,kitty,hyprland,uwsm,zathura,kanshi,xorg}"
DOTFILES="${DOTFILES:-$HOME/.dotfiles}"

# Move into the dotfiles directory
pushd "$DOTFILES" > /dev/null

# Loop through each folder and apply stow
for folder in $(echo "$STOW_FOLDERS" | tr ',' ' ')
do
  echo "stow $folder"
  stow -D "$folder"
  stow "$folder"
done

# Return to previous directory
popd > /dev/null

