#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="zsh,git,bin,git,i3,tmux,nvim"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
